FROM python:3.11-slim AS test

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app
ENV USE_MOCK_DB=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir pytest pytest-cov

COPY app /app/app
COPY tests /app/tests
# COPY pytest.ini /app/pytest.ini

CMD ["bash", "-lc", "mkdir -p /app/reports && pytest -q --maxfail=1 --disable-warnings --junitxml=/app/reports/unit-tests.xml"]
