services:
  backend:
    image: ${IMAGE_BACKEND:-workout-backend}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - MONGO_URI=${MONGO_URI:-mongodb://db:27017/}
      - MONGO_DB_NAME=${MONGO_DB_NAME:-mydatabase}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend.network
      - frontend.network

  frontend:
    image: ${IMAGE_FRONTEND:-workout-frontend}:${TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - frontend.network

  db:
    image: mongo:latest
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - backend.network

volumes:
  mongo_data:

networks:
  backend.network:
    name: backend.network
    driver: bridge

  frontend.network:
    name: frontend.network
    driver: bridge

  # cicd-network:
  #   external: true