version: '3.8'

services:
  backend:
    build: .
    # Internal only; nginx (frontend) will reverse proxy to this
    expose:
      - "8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend.network
      - cicd-network
      - frontend.network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - frontend.network
      - cicd-network

  db:
    image: mongo:latest
    # Internal access only from backend
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - backend.network

volumes:
  mongo_data:

networks:
  backend.network:
    name: backend.network
    driver: bridge

  frontend.network:
    name: frontend.network
    driver: bridge

  cicd-network:
    external: true
